// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dftxpegayetyxofhlvif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdHhwZWdheWV0eXhvZmhsdmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTE2MDYsImV4cCI6MjA3MTg2NzYwNn0.CYVma2dyNHeL4Iy3FbVT9KNd64DryKLuPN7dM__NQm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});